# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1093ad5270d190ffb375e75ff0e3469a74909df8e443bbeb7d08205f7f98af168b73d3d01ccba7796d60acb98f0d1084a4055048d2dcf676c22f9c97a6152103

test:
  secret_key_base: c453b364d4048fb5a5bdd37ce5b5237fbedcbb42c90427f323ad064b0242d2f7750ed6b203dbb3b29de3db68347aa3d3655179c57d3913e8067e119ffdd98eb7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
